spring.application.name=agendamento-service
api.security.token.secret=${JWT_SECRET:12345678}

spring.datasource.url=jdbc:postgresql://localhost:5432/tech-challenge-3-clinica
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.clinica.horario.abertura=7
api.clinica.horario.fechamento=19
api.clinica.antecedencia.minutos=30
api.clinica.dias.fechados=SUNDAY

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

server.port=8081